name: moveit2-server
channels:
  - conda-forge
  - robostack-jazzy
dependencies:
  - python=3.12
  - pip
  - websockets
  - ros-jazzy-ros-base
  - ros-jazzy-rclpy
  - ros-jazzy-geometry-msgs
  - ros-jazzy-moveit-py
  - ros-jazzy-moveit-planners-ompl
  - ros-jazzy-rmw-cyclonedds-cpp
